import type { AggregatedWindow, PatternAlert } from '../aggregator/patterns.js';
import type { InsightReport } from '../store/insights.js';

export function generateMarkdownReport(
  window: AggregatedWindow,
  alerts: PatternAlert[],
  insight: InsightReport
): string {
  const formatTime = (ts: string | number) => new Date(ts).toLocaleTimeString();
  const dateStr = new Date(window.windowStart).toLocaleDateString();

  let md = `# LLM Observability Report
**Service**: ${window.serviceName}
**Window**: ${formatTime(window.windowStart)} - ${formatTime(window.windowEnd)} (${dateStr})
**Duration**: ${window.durationMinutes} minutes

---

## 📊 1. Executive Summary

- **Health Score**: ${insight.healthScore}/100
- **Headline**: ${insight.headline}
- **Total Traces**: ${window.totalTraces} (${(window.totalTraces / window.durationMinutes).toFixed(1)} traces/min)
- **Error Rate**: ${(window.errorRate * 100).toFixed(1)}%

> **AI Summary**: ${insight.summary}

---

## ⏱️ 2. Latency Analysis

- **Average Latency**: ${window.avgLatencyMs.toFixed(0)} ms
- **p50 Latency**: ${window.p50LatencyMs.toFixed(0)} ms
- **p95 Latency**: ${window.p95LatencyMs.toFixed(0)} ms
- **p99 Latency**: ${window.p99LatencyMs.toFixed(0)} ms

> **AI Assessment** (${insight.latencyAnalysis.assessment.toUpperCase()}): 
${insight.latencyAnalysis.concern || 'No significant latency concerns.'}
${insight.latencyAnalysis.recommendation || ''}

---

## 🪙 3. Token & Cost Load

- **Total Tokens**: ${window.totalTokens}
- **Prompt Tokens**: ${window.totalPromptTokens}
- **Completion Tokens**: ${window.totalCompletionTokens}

> **AI Assessment** (Trend: ${insight.tokenAnalysis.trend}):
${insight.tokenAnalysis.concern || 'Token usage is stable.'}
${insight.tokenAnalysis.recommendation || ''}

---

## 🛠️ 4. Tool Usage

- **Most Used Tool**: ${insight.toolAnalysis.mostUsed || 'None'}
- **Total Tool Calls**: ${Object.values(window.toolCallsByName).reduce((a, b) => a + b, 0)}

**Tool Breakdown**:
${Object.entries(window.toolCallsByName).map(([name, count]) => `- \`${name}\`: ${count} calls`).join('\n') || '- No tools utilized in this window.'}

> **AI Assessment**:
${insight.toolAnalysis.concern || 'Tool usage is normal.'}
${insight.toolAnalysis.recommendation || ''}

---

## 🚨 5. AI Findings & Alerts

${insight.findings.length === 0 ? '> No critical findings to report.' : ''}

${insight.findings.map(f => `### [${f.severity.toUpperCase()}] ${f.title}
- **Type**: ${f.type}
- **Affected**: ${f.metric}
- **Detail**: ${f.detail}
- **Recommendation**: ${f.recommendation}
`).join('\n')}

---

## 👁️ 6. What to Watch For Next Window

${insight.watchFor.length === 0 ? '- No upcoming risks identified.' : insight.watchFor.map(w => `- ${w}`).join('\n')}

---
*Report automatically generated by LLM Autopilot Daemon.*
`;

  return md;
}
